# Generated by Django 2.1.5 on 2020-10-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_python_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('ReType_Pass', models.CharField(max_length=40)),
            ],
        ),
    ]
